"""
Centralized authorization / RBAC layer.

Phase 2 only.

Security model
--------------
Authentication is performed exclusively by auth.py.  This module never
accepts a role, user ID, class, section, subject, or student identity from
chat text as proof of authorization.

The trusted caller context must originate from auth.get_current_user():

    {
        "id": "...",
        "role": "teacher|student|parent|principal",
        "name": "..."
    }

The signed JWT is therefore the source of truth for identity.

Authorization rules
-------------------
teacher:
    - Can access only students whose class + section are explicitly assigned
      to the authenticated teacher.
    - Can perform teacher workflows only for assigned class/section.
    - Subject-sensitive operations are additionally restricted to subjects
      listed in auth_teacher.subject_handled.
    - Cannot impersonate another teacher by supplying another teacher_id.

student:
    - Can access only the authenticated student's own records.
    - Cannot request another student's attendance, marks, bio, etc.

parent:
    - Can access only the authenticated parent's child_student_id.
    - child_student_id supplied by the caller is treated only as a requested
      resource and must match the authenticated parent's DB relationship.

principal:
    - School-wide access.
    - No class, section, subject, teacher, or student restriction.

Important:
    This module deliberately fails closed.  Missing/invalid caller fields,
    unknown roles, missing DB records, or malformed authorization data result
    in AuthorizationError rather than an accidental authorization grant.
"""

from __future__ import annotations

from collections.abc import Iterable
from typing import Any

from sqlalchemy.orm import Session

from .model import (
    AuthParent,
    AuthPrincipal,
    AuthStudent,
    AuthTeacher,
    DailyAttendance,
    ExamMarks,
    StudentBio,
    TeacherBio,
)


# ============================================================================
# Constants
# ============================================================================

ALLOWED_ROLES = frozenset(
    {
        "teacher",
        "student",
        "parent",
        "principal",
    }
)

ALLOWED_SUBJECTS = frozenset(
    {
        "Maths",
        "Science",
        "Language",
        "Social",
        "Technology",
    }
)


# ============================================================================
# Exceptions
# ============================================================================

class AuthorizationError(Exception):
    """
    Raised whenever an authenticated caller is not authorized to access
    a requested resource.

    Authorization failures intentionally use a single exception hierarchy
    so callers cannot accidentally continue execution after a failed check.
    """

    def __init__(self, message: str):
        self.message = message
        super().__init__(message)


class ClarificationNeeded(AuthorizationError):
    """
    Indicates that authorization succeeded up to the point where the
    requested resource is ambiguous.

    Example:
        A parent has two children and says "show my child's marks".

    This is not an authorization bypass.  No protected data is returned
    until the caller identifies one of their already-authorized children.
    """

    def __init__(self, message: str, options: list[str]):
        self.options = options
        super().__init__(message)


# ============================================================================
# Caller validation
# ============================================================================

def _caller_role(caller: dict[str, Any]) -> str:
    """
    Extract and validate the role from the verified auth.py caller context.

    Never accepts role aliases or role claims supplied separately by a
    caller/tool.
    """
    if not isinstance(caller, dict):
        raise AuthorizationError("Invalid authenticated user context.")

    role = caller.get("role")

    if not isinstance(role, str):
        raise AuthorizationError("Authenticated user role is missing.")

    role = role.strip().lower()

    if role not in ALLOWED_ROLES:
        raise AuthorizationError("Authenticated user has an invalid role.")

    return role


def _caller_id(caller: dict[str, Any]) -> str:
    """
    Extract the authenticated subject ID generated by auth.py.

    auth.py places the JWT `sub` claim into `caller["id"]`.
    """
    if not isinstance(caller, dict):
        raise AuthorizationError("Invalid authenticated user context.")

    subject_id = caller.get("id")

    if subject_id is None:
        raise AuthorizationError("Authenticated user identity is missing.")

    subject_id = str(subject_id).strip()

    if not subject_id:
        raise AuthorizationError("Authenticated user identity is empty.")

    return subject_id


def _caller_name(caller: dict[str, Any]) -> str:
    """Return the verified display name, or an empty string."""
    name = caller.get("name", "")

    if name is None:
        return ""

    return str(name).strip()


def _normalize(value: Any) -> str:
    """Normalize user-supplied lookup values for safe comparison."""
    if value is None:
        return ""

    return str(value).strip().casefold()


def _normalize_list(value: Any) -> list[str]:
    """
    Normalize JSON/ARRAY values stored in AuthTeacher.

    The current model uses JSONB for classes, sections and subjects.
    This helper also tolerates a legacy scalar value without granting
    broader access.
    """
    if value is None:
        return []

    if isinstance(value, (list, tuple, set)):
        values = value
    else:
        values = [value]

    return [
        str(item).strip()
        for item in values
        if item is not None and str(item).strip()
    ]


# ============================================================================
# Basic RBAC
# ============================================================================

def require_role(
    caller: dict[str, Any],
    *allowed_roles: str,
) -> None:
    """
    Require the authenticated caller to have one of the supplied roles.

    Example:
        require_role(caller, "teacher")
        require_role(caller, "teacher", "principal")

    The caller's role is read exclusively from auth.py's verified JWT
    context.
    """
    actual_role = _caller_role(caller)

    normalized_allowed = {
        str(role).strip().lower()
        for role in allowed_roles
        if role is not None
    }

    if not normalized_allowed:
        raise AuthorizationError("Authorization policy is not configured.")

    if not normalized_allowed.issubset(ALLOWED_ROLES):
        raise AuthorizationError("Authorization policy contains an invalid role.")

    if actual_role not in normalized_allowed:
        role_list = ", ".join(sorted(normalized_allowed))
        raise AuthorizationError(
            f"This action is only available to {role_list} accounts."
        )


def require_student(caller: dict[str, Any]) -> None:
    require_role(caller, "student")


def require_teacher(caller: dict[str, Any]) -> None:
    require_role(caller, "teacher")


def require_parent(caller: dict[str, Any]) -> None:
    require_role(caller, "parent")


def require_principal(caller: dict[str, Any]) -> None:
    require_role(caller, "principal")


# ============================================================================
# Authenticated role record resolution
# ============================================================================

def get_authenticated_teacher(
    db: Session,
    caller: dict[str, Any],
) -> AuthTeacher:
    """
    Resolve the teacher account using ONLY the authenticated JWT subject.

    No teacher_id supplied by chat/request parameters is ever used to
    establish identity.
    """
    require_teacher(caller)

    teacher_id = _caller_id(caller)

    teacher = (
        db.query(AuthTeacher)
        .filter(AuthTeacher.teacher_id == teacher_id)
        .first()
    )

    if teacher is None:
        raise AuthorizationError(
            "Your teacher account could not be found. Please contact the school office."
        )

    return teacher


def get_authenticated_student(
    db: Session,
    caller: dict[str, Any],
) -> AuthStudent:
    """
    Resolve the authenticated student's own account.
    """
    require_student(caller)

    student_id = _caller_id(caller)

    student = (
        db.query(AuthStudent)
        .filter(AuthStudent.student_id == student_id)
        .first()
    )

    if student is None:
        raise AuthorizationError(
            "Your student account could not be found. Please contact the school office."
        )

    return student


def get_authenticated_parent(
    db: Session,
    caller: dict[str, Any],
) -> AuthParent:
    """
    Resolve the authenticated parent account.

    Parent identity comes from the server-generated parent_id contained
    in the JWT, never from a child_student_id or parent ID supplied by
    the request.
    """
    require_parent(caller)

    parent_id = _caller_id(caller)

    parent = (
        db.query(AuthParent)
        .filter(AuthParent.parent_id == parent_id)
        .first()
    )

    if parent is None:
        raise AuthorizationError(
            "Your parent account could not be found. Please contact the school office."
        )

    return parent


def get_authenticated_principal(
    db: Session,
    caller: dict[str, Any],
) -> AuthPrincipal:
    """
    Resolve the authenticated principal account.

    Kept explicit even though principals generally do not need resource
    resolution, because it provides a DB-backed identity check for
    sensitive principal-only operations.
    """
    require_principal(caller)

    principal_id = _caller_id(caller)

    principal = (
        db.query(AuthPrincipal)
        .filter(AuthPrincipal.principal_id == principal_id)
        .first()
    )

    if principal is None:
        raise AuthorizationError(
            "Your principal account could not be found. Please contact the school office."
        )

    return principal


# ============================================================================
# Student authorization
# ============================================================================

def verify_student_access(
    db: Session,
    caller: dict[str, Any],
    student_id: str | None = None,
) -> AuthStudent:
    """
    Verify that a student may access a student record.

    Rules:
        student -> own student_id only
        principal -> any student
        teacher/parent -> denied by this helper

    For a student caller, a missing student_id automatically resolves to
    their authenticated ID.

    If a student explicitly requests another ID, access is denied.
    """
    role = _caller_role(caller)

    if role == "student":
        own_student = get_authenticated_student(db, caller)

        if student_id is not None:
            requested = str(student_id).strip()

            if requested != own_student.student_id:
                raise AuthorizationError(
                    "Students may only access their own student records."
                )

        return own_student

    if role == "principal":
        if student_id is None or not str(student_id).strip():
            raise AuthorizationError("A student ID is required for this lookup.")

        student = (
            db.query(AuthStudent)
            .filter(AuthStudent.student_id == str(student_id).strip())
            .first()
        )

        if student is None:
            raise AuthorizationError("Student record not found.")

        return student

    raise AuthorizationError(
        "This student-access operation is not permitted for your role."
    )


def resolve_own_student(
    db: Session,
    caller: dict[str, Any],
) -> AuthStudent:
    """
    Backwards-compatible helper used by existing tool handlers.

    A student can only resolve their own student account.
    """
    return verify_student_access(db, caller)


# ============================================================================
# Parent -> child authorization
# ============================================================================

def verify_parent_access(
    db: Session,
    caller: dict[str, Any],
    student_id: str | None = None,
) -> AuthStudent:
    """
    Verify that the authenticated parent may access a child.

    The authoritative relationship is AuthParent.child_student_id.

    A parent-supplied student_id is NEVER trusted by itself.  It must equal
    the child_student_id stored on the authenticated parent record.
    """
    parent = get_authenticated_parent(db, caller)

    linked_child_id = str(parent.child_student_id).strip()

    if not linked_child_id:
        raise AuthorizationError(
            "No child is linked to your parent account."
        )

    if student_id is not None:
        requested_id = str(student_id).strip()

        if requested_id != linked_child_id:
            raise AuthorizationError(
                "You are not authorized to access that student's records."
            )

    child = (
        db.query(AuthStudent)
        .filter(AuthStudent.student_id == linked_child_id)
        .first()
    )

    if child is None:
        raise AuthorizationError(
            "The child linked to your account could not be found."
        )

    return child


def resolve_linked_child(
    db: Session,
    caller: dict[str, Any],
    child_name: str | None = None,
) -> AuthStudent:
    """
    Backwards-compatible parent child resolver.

    The new schema permits one child per AuthParent record.  If a parent
    provides a name, the name must match the already-authorized child.
    The name is never used to discover an arbitrary school student.
    """
    child = verify_parent_access(db, caller)

    if child_name:
        requested_name = _normalize(child_name)

        valid_names = {
            _normalize(child.name),
        }

        bio = (
            db.query(StudentBio)
            .filter(StudentBio.student_id == child.student_id)
            .first()
        )

        if bio is not None and bio.student_name:
            valid_names.add(_normalize(bio.student_name))

        if requested_name not in valid_names:
            raise AuthorizationError(
                f"'{child_name}' is not the child linked to your account."
            )

    return child


# ============================================================================
# Teacher class / section scoping
# ============================================================================

def teacher_handles_class_section(
    teacher: AuthTeacher,
    class_name: str,
    section: str,
) -> bool:
    """
    Return whether a teacher is explicitly assigned to the requested
    class + section.

    IMPORTANT:
        AuthTeacher stores classes and sections independently, so the
        schema expresses an allowed class set and an allowed section set.
        Authorization therefore requires membership in BOTH sets.

    This is intentionally strict rather than assuming every class/section
    combination is valid when one dimension matches.
    """
    requested_class = _normalize(class_name)
    requested_section = _normalize(section)

    if not requested_class or not requested_section:
        return False

    assigned_classes = {
        _normalize(value)
        for value in _normalize_list(teacher.classes)
    }

    assigned_sections = {
        _normalize(value)
        for value in _normalize_list(teacher.sections)
    }

    return (
        requested_class in assigned_classes
        and requested_section in assigned_sections
    )


def verify_teacher_access(
    db: Session,
    caller: dict[str, Any],
    *,
    class_name: str | None = None,
    section: str | None = None,
    student_id: str | None = None,
    subject: str | None = None,
) -> AuthTeacher:
    """
    Verify teacher authorization against the teacher's DB-scoped
    assignments.

    Supported checks:
        - teacher role
        - assigned class
        - assigned section
        - assigned student
        - assigned subject

    If student_id is supplied, the student is loaded and its class/section
    must belong to the authenticated teacher.

    Principal is intentionally not accepted here.  Principal operations
    should use require_principal() or their own explicit principal-scoped
    helper so policies cannot accidentally become ambiguous.
    """
    teacher = get_authenticated_teacher(db, caller)

    if class_name is None and section is None and student_id is None and subject is None:
        return teacher

    resolved_class = class_name
    resolved_section = section

    student: AuthStudent | None = None

    if student_id is not None:
        requested_student_id = str(student_id).strip()

        if not requested_student_id:
            raise AuthorizationError("Student ID cannot be empty.")

        student = (
            db.query(AuthStudent)
            .filter(AuthStudent.student_id == requested_student_id)
            .first()
        )

        if student is None:
            raise AuthorizationError("Student record not found.")

        resolved_class = student.class_name
        resolved_section = student.section

    if resolved_class is None or resolved_section is None:
        raise AuthorizationError(
            "Both class and section are required to verify teacher access."
        )

    if not teacher_handles_class_section(
        teacher,
        str(resolved_class),
        str(resolved_section),
    ):
        raise AuthorizationError(
            "You are not authorized to access data for this class and section."
        )

    if student is not None:
        if (
            _normalize(student.class_name) != _normalize(str(resolved_class))
            or _normalize(student.section) != _normalize(str(resolved_section))
        ):
            raise AuthorizationError(
                "The requested student does not belong to the authorized class and section."
            )

    if subject is not None:
        requested_subject = str(subject).strip()

        if requested_subject not in ALLOWED_SUBJECTS:
            raise AuthorizationError("Invalid subject.")

        assigned_subjects = {
            _normalize(value)
            for value in _normalize_list(teacher.subject_handled)
        }

        if _normalize(requested_subject) not in assigned_subjects:
            raise AuthorizationError(
                f"You are not authorized to access {requested_subject} subject data."
            )

    return teacher


def resolve_own_class(
    db: Session,
    caller: dict[str, Any],
) -> tuple[str, str]:
    """
    Resolve a teacher's authorized class/section.

    The new auth_teacher schema stores classes and sections as multi-valued
    JSON arrays.  Therefore this function returns a pair only when there is
    exactly one class and one section.

    For multi-class/multi-section teachers, callers must explicitly specify
    class_name + section and run verify_teacher_access().
    """
    teacher = get_authenticated_teacher(db, caller)

    classes = _normalize_list(teacher.classes)
    sections = _normalize_list(teacher.sections)

    if len(classes) != 1 or len(sections) != 1:
        raise ClarificationNeeded(
            "Your account is assigned to multiple classes or sections. "
            "Please specify the class and section.",
            options=[
                f"{class_name}{section}"
                for class_name in classes
                for section in sections
            ],
        )

    return classes[0], sections[0]


# ============================================================================
# Teacher -> student resolution
# ============================================================================

def resolve_student_in_class(
    db: Session,
    caller: dict[str, Any],
    student_name: str,
    *,
    class_name: str | None = None,
    section: str | None = None,
) -> AuthStudent:
    """
    Resolve exactly one student by name, but ONLY inside a class/section
    already authorized for the authenticated teacher.

    This function never searches the entire school for a teacher.
    """
    teacher = get_authenticated_teacher(db, caller)

    if class_name is None or section is None:
        raise AuthorizationError(
            "Class and section are required for teacher student lookup."
        )

    if not teacher_handles_class_section(teacher, class_name, section):
        raise AuthorizationError(
            "You are not authorized to access that class and section."
        )

    needle = _normalize(student_name)

    if not needle:
        raise AuthorizationError("Student name cannot be empty.")

    students = (
        db.query(AuthStudent)
        .filter(
            AuthStudent.class_name == class_name,
            AuthStudent.section == section,
        )
        .all()
    )

    matches = [
        student
        for student in students
        if needle in _normalize(student.name)
    ]

    if not matches:
        raise AuthorizationError(
            f"No student named '{student_name}' was found in "
            f"{class_name} Section {section}."
        )

    if len(matches) > 1:
        raise ClarificationNeeded(
            f"More than one student matches '{student_name}'. "
            "Please specify the student ID.",
            options=[
                f"{student.name} ({student.student_id})"
                for student in matches
            ],
        )

    return matches[0]


def verify_teacher_student_access(
    db: Session,
    caller: dict[str, Any],
    student_id: str,
    *,
    subject: str | None = None,
) -> AuthStudent:
    """
    Strict teacher -> student authorization.

    The teacher is allowed to access the student only if:
        1. caller role == teacher
        2. teacher exists
        3. student exists
        4. student's class is assigned to teacher
        5. student's section is assigned to teacher
        6. requested subject, if any, is handled by teacher
    """
    student = (
        db.query(AuthStudent)
        .filter(AuthStudent.student_id == str(student_id).strip())
        .first()
    )

    if student is None:
        raise AuthorizationError("Student record not found.")

    verify_teacher_access(
        db,
        caller,
        class_name=student.class_name,
        section=student.section,
        student_id=student.student_id,
        subject=subject,
    )

    return student


# ============================================================================
# Subject authorization
# ============================================================================

def verify_teacher_subject_access(
    db: Session,
    caller: dict[str, Any],
    subject: str,
) -> AuthTeacher:
    """
    Verify that the authenticated teacher teaches the requested subject.
    """
    return verify_teacher_access(
        db,
        caller,
        subject=subject,
    )


# ============================================================================
# Attendance authorization
# ============================================================================

def verify_attendance_access(
    db: Session,
    caller: dict[str, Any],
    *,
    student_id: str | None = None,
    class_name: str | None = None,
    section: str | None = None,
    write: bool = False,
) -> None:
    """
    Authorization policy for attendance.

    Student:
        own attendance only; read-only.

    Parent:
        linked child's attendance only; read-only.

    Teacher:
        assigned class/section only.
        Read and write are permitted for assigned students.

    Principal:
        school-wide attendance access.
        This helper permits read access but deliberately does not grant
        attendance modification to principals.

    `write=True` is therefore valid only for teachers.
    """
    role = _caller_role(caller)

    if role == "student":
        if write:
            raise AuthorizationError(
                "Students cannot modify attendance."
            )

        verify_student_access(db, caller, student_id)
        return

    if role == "parent":
        if write:
            raise AuthorizationError(
                "Parents cannot modify attendance."
            )

        verify_parent_access(db, caller, student_id)
        return

    if role == "principal":
        if write:
            raise AuthorizationError(
                "Principals cannot modify attendance through this operation."
            )
        return

    if role == "teacher":
        if student_id is not None:
            verify_teacher_student_access(
                db,
                caller,
                student_id,
            )
            return

        if class_name is None or section is None:
            raise AuthorizationError(
                "Class and section are required for teacher attendance access."
            )

        verify_teacher_access(
            db,
            caller,
            class_name=class_name,
            section=section,
        )
        return

    raise AuthorizationError("Your role cannot access attendance data.")


# ============================================================================
# Marks authorization
# ============================================================================

def verify_marks_access(
    db: Session,
    caller: dict[str, Any],
    *,
    student_id: str | None = None,
    class_name: str | None = None,
    section: str | None = None,
    subject: str | None = None,
    write: bool = False,
) -> None:
    """
    Authorization policy for exam marks.

    Student:
        own marks, read-only.

    Parent:
        linked child's marks, read-only.

    Teacher:
        assigned class/section and, when supplied, assigned subject.
        Teachers may write marks only within their assigned scope.

    Principal:
        unrestricted read access.
        Modification is intentionally denied by this generic helper.
    """
    role = _caller_role(caller)

    if role == "student":
        if write:
            raise AuthorizationError(
                "Students cannot modify exam marks."
            )

        verify_student_access(db, caller, student_id)
        return

    if role == "parent":
        if write:
            raise AuthorizationError(
                "Parents cannot modify exam marks."
            )

        verify_parent_access(db, caller, student_id)
        return

    if role == "principal":
        if write:
            raise AuthorizationError(
                "Principals cannot modify exam marks through this operation."
            )
        return

    if role == "teacher":
        if student_id is not None:
            verify_teacher_student_access(
                db,
                caller,
                student_id,
                subject=subject,
            )
            return

        if class_name is None or section is None:
            raise AuthorizationError(
                "Class and section are required for teacher marks access."
            )

        verify_teacher_access(
            db,
            caller,
            class_name=class_name,
            section=section,
            subject=subject,
        )
        return

    raise AuthorizationError("Your role cannot access exam marks.")


# ============================================================================
# Bio/profile authorization
# ============================================================================

def verify_student_bio_access(
    db: Session,
    caller: dict[str, Any],
    student_id: str,
) -> AuthStudent:
    """
    Verify access to student_bio through the corresponding authenticated
    student record.

    Teacher:
        only students in assigned class/section.

    Student:
        own bio.

    Parent:
        linked child's bio.

    Principal:
        any student's bio.
    """
    role = _caller_role(caller)

    if role == "student":
        return verify_student_access(db, caller, student_id)

    if role == "parent":
        return verify_parent_access(db, caller, student_id)

    if role == "teacher":
        return verify_teacher_student_access(db, caller, student_id)

    if role == "principal":
        student = (
            db.query(AuthStudent)
            .filter(AuthStudent.student_id == str(student_id).strip())
            .first()
        )

        if student is None:
            raise AuthorizationError("Student record not found.")

        return student

    raise AuthorizationError(
        "Your role cannot access student profile information."
    )


def verify_teacher_bio_access(
    db: Session,
    caller: dict[str, Any],
    teacher_id: str | None = None,
) -> AuthTeacher:
    """
    Verify access to teacher_bio.

    Teacher:
        own profile only.

    Principal:
        any teacher profile.

    Student/Parent:
        cannot use this unrestricted teacher-bio lookup.
    """
    role = _caller_role(caller)

    if role == "teacher":
        own_teacher = get_authenticated_teacher(db, caller)

        if teacher_id is not None and str(teacher_id).strip() != own_teacher.teacher_id:
            raise AuthorizationError(
                "Teachers may only access their own teacher profile."
            )

        return own_teacher

    if role == "principal":
        if teacher_id is None or not str(teacher_id).strip():
            raise AuthorizationError("Teacher ID is required.")

        teacher = (
            db.query(AuthTeacher)
            .filter(AuthTeacher.teacher_id == str(teacher_id).strip())
            .first()
        )

        if teacher is None:
            raise AuthorizationError("Teacher record not found.")

        return teacher

    raise AuthorizationError(
        "Your role cannot access teacher profile information."
    )


# ============================================================================
# Principal authorization
# ============================================================================

def verify_principal_access(
    db: Session,
    caller: dict[str, Any],
) -> AuthPrincipal:
    """
    Verify that the caller is the authenticated principal and that the
    principal account still exists in the database.
    """
    return get_authenticated_principal(db, caller)


# ============================================================================
# Communication authorization
# ============================================================================

def verify_teacher_communication_access(
    db: Session,
    caller: dict[str, Any],
    *,
    target_teacher_id: str,
    target_student_id: str | None = None,
    subject: str | None = None,
    message_type: str | None = None,
) -> None:
    """
    Verify that a communication can be sent to a teacher.

    Student:
        may contact only teachers who teach the student's class/section.
        If subject is supplied, the target teacher must teach that subject.

    Parent:
        may contact only teachers who teach the linked child's class/section.
        If subject is supplied, the target teacher must teach that subject.

    Teacher:
        may communicate as themselves; when targeting a student, the student
        must belong to the teacher's assigned class/section.

    Principal:
        school-wide communication access.
    """
    role = _caller_role(caller)

    if not target_teacher_id or not str(target_teacher_id).strip():
        raise AuthorizationError("Target teacher ID is required.")

    target_teacher = (
        db.query(AuthTeacher)
        .filter(AuthTeacher.teacher_id == str(target_teacher_id).strip())
        .first()
    )

    if target_teacher is None:
        raise AuthorizationError("Target teacher not found.")

    if role == "principal":
        return

    if role == "teacher":
        own_teacher = get_authenticated_teacher(db, caller)

        if target_teacher.teacher_id != own_teacher.teacher_id:
            raise AuthorizationError(
                "Teachers may not impersonate another teacher when sending messages."
            )

        if target_student_id is not None:
            verify_teacher_student_access(
                db,
                caller,
                target_student_id,
                subject=subject,
            )

        return

    if role == "student":
        student = get_authenticated_student(db, caller)

    elif role == "parent":
        student = verify_parent_access(db, caller)

    else:
        raise AuthorizationError(
            "Your role cannot send teacher communications."
        )

    if not teacher_handles_class_section(
        target_teacher,
        student.class_name,
        student.section,
    ):
        raise AuthorizationError(
            "You can only contact teachers assigned to your class and section."
        )

    if subject is not None:
        requested_subject = str(subject).strip()

        if requested_subject not in ALLOWED_SUBJECTS:
            raise AuthorizationError("Invalid subject.")

        teacher_subjects = {
            _normalize(value)
            for value in _normalize_list(target_teacher.subject_handled)
        }

        if _normalize(requested_subject) not in teacher_subjects:
            raise AuthorizationError(
                "The selected teacher does not handle that subject."
            )


def verify_warning_access(
    db: Session,
    caller: dict[str, Any],
    target_student_id: str,
) -> AuthStudent:
    """
    Warning creation is a teacher-only operation.

    The teacher must be assigned to the target student's class/section.
    """
    require_teacher(caller)

    return verify_teacher_student_access(
        db,
        caller,
        target_student_id,
    )


# ============================================================================
# Query scoping helpers
# ============================================================================

def authorized_student_ids(
    db: Session,
    caller: dict[str, Any],
    *,
    class_name: str | None = None,
    section: str | None = None,
) -> list[str]:
    """
    Return the exact student IDs visible to the authenticated caller.

    This helper is useful for analytics/reporting queries because the caller
    should first obtain an authorization scope and only then query marks,
    attendance, etc.

    Scope:
        principal -> all students, optionally filtered by class/section
        student   -> own student
        parent    -> linked child
        teacher   -> assigned class/section, optionally narrowed by the
                     explicitly requested class/section
    """
    role = _caller_role(caller)

    query = db.query(AuthStudent)

    if role == "principal":
        if class_name is not None:
            query = query.filter(AuthStudent.class_name == class_name)

        if section is not None:
            query = query.filter(AuthStudent.section == section)

        return [
            student.student_id
            for student in query.all()
        ]

    if role == "student":
        student = get_authenticated_student(db, caller)

        if class_name is not None and _normalize(student.class_name) != _normalize(class_name):
            raise AuthorizationError(
                "Students cannot query another class."
            )

        if section is not None and _normalize(student.section) != _normalize(section):
            raise AuthorizationError(
                "Students cannot query another section."
            )

        return [student.student_id]

    if role == "parent":
        child = verify_parent_access(db, caller)

        if class_name is not None and _normalize(child.class_name) != _normalize(class_name):
            raise AuthorizationError(
                "The requested class is outside your child's scope."
            )

        if section is not None and _normalize(child.section) != _normalize(section):
            raise AuthorizationError(
                "The requested section is outside your child's scope."
            )

        return [child.student_id]

    if role == "teacher":
        teacher = get_authenticated_teacher(db, caller)

        if class_name is not None or section is not None:
            if class_name is None or section is None:
                raise AuthorizationError(
                    "Both class and section must be supplied together."
                )

            if not teacher_handles_class_section(
                teacher,
                class_name,
                section,
            ):
                raise AuthorizationError(
                    "You are not authorized to access that class and section."
                )

            query = query.filter(
                AuthStudent.class_name == class_name,
                AuthStudent.section == section,
            )

            return [
                student.student_id
                for student in query.all()
            ]

        assigned_classes = _normalize_list(teacher.classes)
        assigned_sections = _normalize_list(teacher.sections)

        if not assigned_classes or not assigned_sections:
            raise AuthorizationError(
                "No class/section assignments are configured for your account."
            )

        students = query.all()

        return [
            student.student_id
            for student in students
            if teacher_handles_class_section(
                teacher,
                student.class_name,
                student.section,
            )
        ]

    raise AuthorizationError("Unsupported role.")


def scope_students_query(
    db: Session,
    caller: dict[str, Any],
    query,
):
    """
    Apply authorization filtering to an existing AuthStudent query.

    Returns a SQLAlchemy query restricted to the caller's permitted student
    records.

    This is preferable to:
        query.all()
        then filtering in Python

    because unauthorized rows never leave the database query boundary.
    """
    role = _caller_role(caller)

    if role == "principal":
        return query

    if role == "student":
        student_id = _caller_id(caller)
        return query.filter(AuthStudent.student_id == student_id)

    if role == "parent":
        parent_id = _caller_id(caller)

        parent = (
            db.query(AuthParent)
            .filter(AuthParent.parent_id == parent_id)
            .first()
        )

        if parent is None:
            raise AuthorizationError("Parent account not found.")

        return query.filter(
            AuthStudent.student_id == parent.child_student_id
        )

    if role == "teacher":
        teacher = get_authenticated_teacher(db, caller)

        students = (
            db.query(AuthStudent)
            .filter(
                AuthStudent.class_name.in_(
                    _normalize_list(teacher.classes)
                ),
                AuthStudent.section.in_(
                    _normalize_list(teacher.sections)
                ),
            )
            .subquery()
        )

        return query.filter(
            AuthStudent.student_id.in_(
                db.query(students.c.student_id)
            )
        )

    raise AuthorizationError("Unsupported role.")


# ============================================================================
# Resource-level guards for existing ORM records
# ============================================================================

def can_access_student(
    db: Session,
    caller: dict[str, Any],
    student_id: str,
) -> bool:
    """
    Boolean convenience wrapper around verify_student_bio_access().

    Security-sensitive code should generally use the raising version so
    authorization failures cannot accidentally be ignored.
    """
    try:
        verify_student_bio_access(db, caller, student_id)
        return True
    except AuthorizationError:
        return False


def can_access_teacher(
    db: Session,
    caller: dict[str, Any],
    teacher_id: str,
) -> bool:
    """Boolean convenience wrapper for teacher profile access."""
    try:
        verify_teacher_bio_access(db, caller, teacher_id)
        return True
    except AuthorizationError:
        return False


# ============================================================================
# Compatibility helpers
# ============================================================================

def resolve_teacher_student(
    db: Session,
    caller: dict[str, Any],
    student_id: str,
) -> AuthStudent:
    """
    Explicit replacement for old-style arbitrary student resolution.

    Never call:
        db.query(AuthStudent).get(student_id)

    from a tool without first invoking this guard.
    """
    role = _caller_role(caller)

    if role == "student":
        return verify_student_access(db, caller, student_id)

    if role == "parent":
        return verify_parent_access(db, caller, student_id)

    if role == "teacher":
        return verify_teacher_student_access(db, caller, student_id)

    if role == "principal":
        student = (
            db.query(AuthStudent)
            .filter(AuthStudent.student_id == str(student_id).strip())
            .first()
        )

        if student is None:
            raise AuthorizationError("Student record not found.")

        return student

    raise AuthorizationError("Unsupported role.")


# ============================================================================
# Defensive validation for analytics/reporting
# ============================================================================

def verify_report_scope(
    db: Session,
    caller: dict[str, Any],
    *,
    class_name: str | None = None,
    section: str | None = None,
    subject: str | None = None,
) -> list[str]:
    """
    Authorize an analytics/report scope and return the exact student IDs
    that may participate in the report.

    This prevents an LLM-generated report query such as:

        "all failing Science students"

    from bypassing the caller's data boundary.

    Teacher:
        class + section must be explicitly assigned.
        subject, if specified, must be taught by the teacher.

    Student:
        only their own student record.

    Parent:
        only their linked child.

    Principal:
        unrestricted school-wide report scope.
    """
    role = _caller_role(caller)

    if role == "teacher":
        if class_name is None or section is None:
            raise AuthorizationError(
                "Teachers must specify an authorized class and section "
                "for analytical reports."
            )

        verify_teacher_access(
            db,
            caller,
            class_name=class_name,
            section=section,
            subject=subject,
        )

        return authorized_student_ids(
            db,
            caller,
            class_name=class_name,
            section=section,
        )

    if role == "student":
        if class_name is not None or section is not None:
            student = get_authenticated_student(db, caller)

            if class_name is not None and _normalize(student.class_name) != _normalize(class_name):
                raise AuthorizationError(
                    "Students cannot request reports for another class."
                )

            if section is not None and _normalize(student.section) != _normalize(section):
                raise AuthorizationError(
                    "Students cannot request reports for another section."
                )

        if subject is not None and subject not in ALLOWED_SUBJECTS:
            raise AuthorizationError("Invalid subject.")

        return authorized_student_ids(db, caller)

    if role == "parent":
        child = verify_parent_access(db, caller)

        if class_name is not None and _normalize(child.class_name) != _normalize(class_name):
            raise AuthorizationError(
                "The requested report is outside your child's scope."
            )

        if section is not None and _normalize(child.section) != _normalize(section):
            raise AuthorizationError(
                "The requested report is outside your child's scope."
            )

        if subject is not None and subject not in ALLOWED_SUBJECTS:
            raise AuthorizationError("Invalid subject.")

        return [child.student_id]

    if role == "principal":
        if subject is not None and subject not in ALLOWED_SUBJECTS:
            raise AuthorizationError("Invalid subject.")

        return authorized_student_ids(
            db,
            caller,
            class_name=class_name,
            section=section,
        )

    raise AuthorizationError("Unsupported role.")


# ============================================================================
# Audit-friendly authorization description
# ============================================================================

def authorization_context(
    db: Session,
    caller: dict[str, Any],
) -> dict[str, Any]:
    """
    Return a non-sensitive authorization snapshot useful for logging.

    No password/hash/token material is returned.

    This function is deliberately informational; callers must still execute
    the appropriate verify_* guard before accessing a protected resource.
    """
    role = _caller_role(caller)
    subject_id = _caller_id(caller)

    context: dict[str, Any] = {
        "id": subject_id,
        "role": role,
        "name": _caller_name(caller),
    }

    if role == "teacher":
        teacher = get_authenticated_teacher(db, caller)

        context.update(
            {
                "classes": _normalize_list(teacher.classes),
                "sections": _normalize_list(teacher.sections),
                "subjects": _normalize_list(teacher.subject_handled),
            }
        )

    elif role == "student":
        student = get_authenticated_student(db, caller)

        context.update(
            {
                "class_name": student.class_name,
                "section": student.section,
            }
        )

    elif role == "parent":
        parent = get_authenticated_parent(db, caller)

        context.update(
            {
                "child_student_id": parent.child_student_id,
            }
        )

    return context